export const LOGIN_HTML = `<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="color-scheme" content="light dark">
    <title>Sign in - frpc dashboard</title>
    <style>
        :root{color-scheme:light;--canvas:#fff;--subtle:#f6f8fa;--fg:#1f2328;--muted:#656d76;--border:#d0d7de;--accent:#0969da;--bad:#cf222e;--bad-bg:#ffebe9}@media(prefers-color-scheme:dark){:root{color-scheme:dark;--canvas:#0d1117;--subtle:#161b22;--fg:#e6edf3;--muted:#8b949e;--border:#30363d;--accent:#58a6ff;--bad:#f85149;--bad-bg:#2d1619}}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:var(--canvas);color:var(--fg);font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans",Helvetica,Arial,sans-serif;letter-spacing:0}.login{width:100%;max-width:340px}.brand{display:flex;align-items:center;justify-content:center;gap:11px;margin-bottom:22px}.mark{width:38px;height:38px;display:grid;place-items:center;border-radius:6px;background:var(--fg);color:var(--canvas);font:600 15px/1 ui-monospace,monospace}.brand strong{font-size:18px}.panel{overflow:hidden;border:1px solid var(--border);border-radius:6px;background:var(--canvas)}.head{padding:16px;border-bottom:1px solid var(--border);background:var(--subtle)}h1{margin:0;font-size:16px;font-weight:600}.server{margin-top:2px;color:var(--muted);font:11px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace}.form{padding:16px}.field{margin-bottom:14px}label{display:block;margin-bottom:5px;font-size:12px;font-weight:600}input{width:100%;height:34px;padding:6px 10px;border:1px solid var(--border);border-radius:6px;background:var(--canvas);color:var(--fg);font:inherit;letter-spacing:0}input:focus-visible,button:focus-visible{outline:2px solid var(--accent);outline-offset:2px}.error{margin-bottom:14px;padding:9px 10px;border:1px solid color-mix(in srgb,var(--bad) 35%,var(--border));border-radius:6px;background:var(--bad-bg);color:var(--bad);font-size:12px}.submit{width:100%;min-height:34px;border:1px solid rgba(31,35,40,.15);border-radius:6px;background:#1f883d;color:#fff;font:inherit;font-weight:600;cursor:pointer}.submit:hover{background:#1a7f37}.submit:disabled{opacity:.6;cursor:not-allowed}.foot{margin-top:12px;color:var(--muted);font-size:11px;text-align:center}
    </style>
</head>
<body>
    <main class="login">
        <div class="brand"><span class="mark">fr</span><strong>frpc dashboard</strong></div>
        <section class="panel">
            <header class="head"><h1>Sign in</h1><div class="server" id="server">local dashboard</div></header>
            <form class="form" id="form">
                <div class="error" id="error" role="alert" hidden></div>
                <div class="field"><label for="username">Username</label><input id="username" name="username" autocomplete="username" required autofocus></div>
                <div class="field"><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="current-password" required></div>
                <button class="submit" id="submit" type="submit">Sign in</button>
            </form>
        </section>
        <div class="foot">Credentials are kept for this tab only.</div>
    </main>
    <script>
        const form=document.getElementById('form'),errorBox=document.getElementById('error'),submit=document.getElementById('submit');
        function encode(value){return btoa(String.fromCharCode(...new TextEncoder().encode(value)))}
        async function verify(auth){const response=await fetch('/api/status',{cache:'no-store',headers:auth?{Authorization:auth}:{}});if(response.ok){const data=await response.json();document.getElementById('server').textContent=data.server||'local dashboard';return true}return false}
        document.getElementById('server').textContent=location.host;
        (async()=>{const saved=sessionStorage.getItem('frpc-auth');try{if(saved&&await verify(saved)){location.replace('/');return}if(saved)sessionStorage.removeItem('frpc-auth');await verify('')}catch{}})();
        form.addEventListener('submit',async(event)=>{event.preventDefault();errorBox.hidden=true;submit.disabled=true;submit.textContent='Signing in...';const data=new FormData(form),auth='Basic '+encode(String(data.get('username'))+':'+String(data.get('password')));try{if(!await verify(auth))throw new Error('Invalid username or password.');sessionStorage.setItem('frpc-auth',auth);location.replace('/')}catch(error){errorBox.textContent=error.message||'Unable to reach the dashboard.';errorBox.hidden=false;document.getElementById('password').select()}finally{submit.disabled=false;submit.textContent='Sign in'}});
    </script>
</body>
</html>`;

export const DASHBOARD_HTML = `<!doctype html>
<html lang="en" x-data="dashboard" :data-theme="theme">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="color-scheme" content="light dark">
    <title>frpc dashboard</title>
    <style>
        :root{color-scheme:light;--canvas:#fff;--subtle:#f6f8fa;--inset:#eaeef2;--fg:#1f2328;--muted:#656d76;--border:#d0d7de;--line:#eaeef2;--accent:#0969da;--accent-bg:#ddf4ff;--ok:#1a7f37;--ok-bg:#dafbe1;--warn:#9a6700;--warn-bg:#fff8c5;--bad:#cf222e;--bad-bg:#ffebe9}
        [data-theme=dark]{color-scheme:dark;--canvas:#0d1117;--subtle:#161b22;--inset:#21262d;--fg:#e6edf3;--muted:#8b949e;--border:#30363d;--line:#21262d;--accent:#58a6ff;--accent-bg:#121d2f;--ok:#3fb950;--ok-bg:#12261a;--warn:#d29922;--warn-bg:#2b2111;--bad:#f85149;--bad-bg:#2d1619}
        *{box-sizing:border-box}html{min-width:320px;background:var(--canvas);scroll-behavior:smooth}body{margin:0;min-height:100vh;background:var(--canvas);color:var(--fg);font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans",Helvetica,Arial,sans-serif;letter-spacing:0}button,input,select{font:inherit;letter-spacing:0}[x-cloak]{display:none!important}.mono{font-family:ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace}
        .shell{min-height:100vh}.header{position:sticky;top:0;z-index:20;border-bottom:1px solid var(--border);background:color-mix(in srgb,var(--canvas) 94%,transparent);backdrop-filter:blur(12px)}.header-main{height:64px;max-width:1440px;margin:auto;padding:0 24px;display:flex;align-items:center;justify-content:space-between;gap:20px}.identity{display:flex;align-items:center;gap:12px;min-width:0}.mark{width:34px;height:34px;display:grid;place-items:center;border-radius:6px;background:var(--fg);color:var(--canvas);font:600 14px/1 ui-monospace,monospace}.product{font-size:17px;font-weight:600;line-height:1.25}.endpoint{max-width:420px;color:var(--muted);font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.actions{display:flex;align-items:center;gap:8px}.btn{min-height:32px;padding:5px 12px;border:1px solid var(--border);border-radius:6px;background:var(--subtle);color:var(--fg);cursor:pointer}.btn:hover{background:var(--inset)}.btn:disabled{opacity:.55;cursor:not-allowed}.icon-btn{width:32px;padding:0;font-size:16px}.btn:focus-visible,input:focus-visible,select:focus-visible,a:focus-visible,.proxy-toggle:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
        .status{display:inline-flex;align-items:center;gap:7px;min-height:28px;padding:3px 10px;border:1px solid var(--border);border-radius:999px;background:var(--subtle);color:var(--muted);font-size:12px;white-space:nowrap}.dot{width:8px;height:8px;flex:none;border-radius:50%;background:currentColor}.status.active{color:var(--ok);border-color:color-mix(in srgb,var(--ok) 35%,var(--border));background:var(--ok-bg)}.status.pending{color:var(--warn);border-color:color-mix(in srgb,var(--warn) 35%,var(--border));background:var(--warn-bg)}.status.error{color:var(--bad);border-color:color-mix(in srgb,var(--bad) 35%,var(--border));background:var(--bad-bg)}
        .subnav{max-width:1440px;height:38px;margin:auto;padding:0 24px;display:flex;align-items:end;gap:24px}.subnav a{height:38px;display:flex;align-items:center;border-bottom:2px solid transparent;color:var(--muted);text-decoration:none;font-size:12px}.subnav a:hover{color:var(--fg);border-color:var(--border)}
        main{max-width:1440px;margin:auto;padding:20px 24px 40px}.notice{margin-bottom:14px;padding:11px 14px;display:flex;align-items:flex-start;justify-content:space-between;gap:16px;border:1px solid color-mix(in srgb,var(--bad) 35%,var(--border));border-radius:6px;background:var(--bad-bg)}.notice strong{display:block;color:var(--bad)}.notice span{color:var(--fg);overflow-wrap:anywhere}
        .metrics{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));margin-bottom:14px;border:1px solid var(--border);border-radius:6px;overflow:hidden}.metric{min-width:0;padding:13px 15px;border-right:1px solid var(--border)}.metric:last-child{border:0}.label{color:var(--muted);font-size:12px}.value{margin-top:3px;overflow:hidden;font-size:20px;line-height:1.35;font-weight:600;text-overflow:ellipsis;white-space:nowrap}.meta{margin-top:1px;overflow:hidden;color:var(--muted);font-size:11px;text-overflow:ellipsis;white-space:nowrap}
        .layout{display:grid;grid-template-columns:minmax(0,2fr) minmax(320px,1fr);gap:14px;align-items:start}.span-all{grid-column:1/-1}.panel{border:1px solid var(--border);border-radius:6px;background:var(--canvas);overflow:hidden}.panel+.panel{margin-top:14px}.panel-head{min-height:50px;padding:9px 14px;display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:1px solid var(--border);background:var(--subtle)}.panel-title{margin:0;font-size:14px;font-weight:600}.panel-sub{color:var(--muted);font-size:11px}.tools{display:flex;align-items:center;gap:7px}.search{height:30px;width:220px;padding:4px 9px;border:1px solid var(--border);border-radius:6px;background:var(--canvas);color:var(--fg)}.select{height:30px;padding:3px 26px 3px 8px;border:1px solid var(--border);border-radius:6px;background:var(--canvas);color:var(--fg)}
        .table-wrap{overflow-x:auto}table{width:100%;min-width:760px;border-collapse:collapse;table-layout:fixed}th,td{padding:9px 14px;border-bottom:1px solid var(--line);text-align:left;vertical-align:middle}th{color:var(--muted);font-size:11px;font-weight:600}tbody tr:last-child td{border-bottom:0}.proxy-row:hover{background:var(--subtle)}.proxy-toggle{width:100%;padding:0;border:0;background:transparent;color:var(--fg);text-align:left;cursor:pointer}.proxy-name{font-weight:600;overflow-wrap:anywhere}.proxy-route,.proxy-local{overflow:hidden;color:var(--muted);font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;text-overflow:ellipsis;white-space:nowrap}.bad-text{margin-top:2px;color:var(--bad);font-size:11px;overflow-wrap:anywhere}.type{display:inline-flex;padding:1px 7px;border:1px solid var(--border);border-radius:999px;background:var(--subtle);font:11px/1.5 ui-monospace,monospace;text-transform:uppercase}.tags{display:flex;flex-wrap:wrap;gap:4px}.tag{padding:1px 6px;border-radius:4px;background:var(--inset);color:var(--muted);font-size:10px;white-space:nowrap}.detail-row td{padding:0;background:var(--subtle)}.details{padding:12px 14px 14px 40px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px 18px;border-bottom:1px solid var(--line)}.detail-label{color:var(--muted);font-size:10px}.detail-value{margin-top:2px;overflow-wrap:anywhere;font-size:12px}
        .empty{min-height:180px;padding:30px;display:grid;place-items:center;text-align:center}.empty h3{margin:0 0 4px;font-size:15px}.empty p{max-width:420px;margin:0 0 12px;color:var(--muted)}.skeleton{height:38px;margin:11px 14px;border-radius:4px;background:linear-gradient(90deg,var(--inset) 25%,var(--subtle) 50%,var(--inset) 75%);background-size:200% 100%;animation:shine 1.3s linear infinite}@keyframes shine{to{background-position:-200% 0}}
        .kv{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.kv-item{min-width:0;padding:11px 14px;border-bottom:1px solid var(--line)}.kv-item:nth-child(odd){border-right:1px solid var(--line)}.kv-item:nth-last-child(-n+2){border-bottom:0}.kv-value{margin-top:2px;overflow-wrap:anywhere;font-size:12px}.flag-on{color:var(--ok)}.flag-off{color:var(--muted)}
        .pool-grid{display:grid;grid-template-columns:repeat(3,1fr)}.pool-item{padding:11px 14px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.pool-item:nth-child(3n){border-right:0}.pool-item:nth-last-child(-n+3){border-bottom:0}.pool-number{font:600 17px/1.4 ui-monospace,monospace}.events{max-height:340px;overflow:auto}.event{display:grid;grid-template-columns:68px 12px minmax(0,1fr);gap:8px;padding:9px 14px;border-bottom:1px solid var(--line)}.event:last-child{border:0}.event-time{color:var(--muted);font:10px/1.6 ui-monospace,monospace}.event-mark{width:7px;height:7px;margin-top:5px;border-radius:50%;background:var(--muted)}.event-mark.success{background:var(--ok)}.event-mark.warning{background:var(--warn)}.event-mark.error{background:var(--bad)}.event-text{font-size:11px;overflow-wrap:anywhere}.memory{height:6px;margin-top:6px;overflow:hidden;border-radius:3px;background:var(--inset)}.memory span{display:block;height:100%;background:var(--accent)}
        .visitor-list{display:grid}.visitor{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:12px;align-items:center;padding:10px 14px;border-bottom:1px solid var(--line)}.visitor:last-child{border:0}.visitor small{display:block;color:var(--muted)}.foot{padding:12px 2px 0;color:var(--muted);font-size:11px;text-align:right}
        @media(max-width:1100px){.metrics{grid-template-columns:repeat(3,1fr)}.metric:nth-child(3){border-right:0}.metric:nth-child(-n+3){border-bottom:1px solid var(--border)}.layout{grid-template-columns:1fr}.span-all{grid-column:auto}.panel+.panel{margin-top:0}.right .panel+.panel{margin-top:14px}.details{grid-template-columns:repeat(2,1fr)}}
        @media(max-width:700px){.header-main{height:auto;min-height:60px;padding:9px 14px}.endpoint{max-width:180px}.action-label,.status-label{display:none}.subnav{padding:0 14px;gap:18px;overflow-x:auto}main{padding:14px}.metrics{grid-template-columns:repeat(2,1fr)}.metric{border-bottom:1px solid var(--border)}.metric:nth-child(2n){border-right:0}.metric:nth-last-child(-n+2){border-bottom:0}.panel-head{align-items:flex-start;flex-direction:column}.tools{width:100%}.search{width:100%;min-width:0}.table-wrap{overflow:visible}.table-wrap table{min-width:0}.table-wrap thead{display:none}.table-wrap tbody{display:block;border-bottom:1px solid var(--border)}.table-wrap tbody:last-child{border-bottom:0}.proxy-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px 16px;padding:12px 14px}.proxy-row td{padding:0;border:0;min-width:0}.proxy-row td:first-child{grid-column:1/-1;grid-row:1}.proxy-row td:nth-child(2){grid-column:1;grid-row:2}.proxy-row td:nth-child(3){grid-column:1/-1;grid-row:3}.proxy-row td:nth-child(4){grid-column:1/-1;grid-row:4}.proxy-row td:nth-child(5){grid-column:1/-1;grid-row:5}.proxy-row td:nth-child(6){grid-column:2;grid-row:2}.proxy-row td[data-label]::before{content:attr(data-label);display:block;margin-bottom:2px;color:var(--muted);font:10px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.detail-row{display:block}.detail-row td{display:block}.details{padding:12px 14px}.kv{grid-template-columns:1fr}.kv-item,.kv-item:nth-child(odd),.kv-item:nth-last-child(-n+2){border-right:0;border-bottom:1px solid var(--line)}.kv-item:last-child{border-bottom:0}.visitor{grid-template-columns:1fr auto}.visitor>div:nth-child(2),.visitor>div:nth-child(3){grid-column:1/-1}.event{grid-template-columns:56px 10px minmax(0,1fr)}}
        @media(max-width:430px){.product{font-size:15px}.endpoint{max-width:140px}.metrics{grid-template-columns:1fr}.metric,.metric:nth-child(3),.metric:nth-last-child(-n+2){border-right:0;border-bottom:1px solid var(--border)}.metric:last-child{border-bottom:0}.tools{flex-direction:column}.select{width:100%}.details{grid-template-columns:1fr}.pool-grid{grid-template-columns:repeat(2,1fr)}.pool-item,.pool-item:nth-child(3n),.pool-item:nth-last-child(-n+3){border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.pool-item:nth-child(2n){border-right:0}.pool-item:nth-last-child(-n+2){border-bottom:0}}
        @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation-duration:.01ms!important;animation-iteration-count:1!important}}
    </style>
    <script>
        document.addEventListener('alpine:init',()=>Alpine.data('dashboard',()=>({
            data:null,loading:true,refreshing:false,error:'',query:'',stateFilter:'all',typeFilter:'all',expanded:null,theme:localStorage.getItem('frpc-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'),clock:Date.now(),
            async init(){await this.load();this.poll=setInterval(()=>this.load(true),2000);setInterval(()=>this.clock=Date.now(),1000)},
            async load(background=false){if(!background)this.refreshing=true;const c=new AbortController(),t=setTimeout(()=>c.abort(),10000),auth=sessionStorage.getItem('frpc-auth');try{const r=await fetch('/api/status',{cache:'no-store',signal:c.signal,headers:auth?{Authorization:auth}:{}});if(r.status===401){sessionStorage.removeItem('frpc-auth');location.replace('/login');return}if(!r.ok)throw new Error('Dashboard API returned HTTP '+r.status);this.data=await r.json();this.error=''}catch(e){this.error=e.name==='AbortError'?'Status request timed out after 10 seconds.':(e.message||String(e))}finally{clearTimeout(t);this.loading=false;this.refreshing=false}},
            toggleTheme(){this.theme=this.theme==='dark'?'light':'dark';localStorage.setItem('frpc-theme',this.theme)},
            logout(){sessionStorage.removeItem('frpc-auth');location.replace('/login')},
            get proxies(){return this.data?.proxies||[]},get visitors(){return this.data?.visitors||[]},get events(){return this.data?.events||[]},
            get types(){return [...new Set(this.proxies.map(p=>p.type))].sort()},
            get filtered(){const q=this.query.trim().toLowerCase();return this.proxies.filter(p=>(this.stateFilter==='all'||p.status===this.stateFilter)&&(this.typeFilter==='all'||p.type===this.typeFilter)&&(!q||[p.name,p.type,p.localTarget,p.remoteAddr,p.route,p.error,...p.features].filter(Boolean).join(' ').toLowerCase().includes(q)))},
            count(s){return this.proxies.filter(p=>p.status===s).length},statusClass(s){return s==='active'?'active':s==='error'?'error':'pending'},connectionClass(){return this.data?.connectionState==='connected'?'active':['connecting','reconnecting'].includes(this.data?.connectionState)?'pending':'error'},
            connectionLabel(){const m={starting:'Starting',connecting:'Connecting',connected:'Connected',reconnecting:'Reconnecting',disconnected:'Disconnected',stopped:'Stopped'};return m[this.data?.connectionState]||'Unavailable'},
            fmtBytes(v){if(!Number.isFinite(v)||v<=0)return'0 B';const u=['B','KB','MB','GB','TB'];let n=v,i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]},
            fmtDuration(v){let n=Math.max(0,Number(v)||0),d=Math.floor(n/86400),h=Math.floor(n%86400/3600),m=Math.floor(n%3600/60),s=Math.floor(n%60);return d?d+'d '+h+'h':h?h+'h '+m+'m':m?m+'m '+s+'s':s+'s'},
            age(v){if(!v)return'never';const s=Math.max(0,Math.floor((this.clock-new Date(v).getTime())/1000));return s<2?'just now':s<60?s+'s ago':Math.floor(s/60)+'m ago'},time(v){return v?new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'-'},
            memoryPercent(){const u=this.data?.memory?.heapUsed||0,t=this.data?.memory?.heapTotal||0;return t?Math.min(100,Math.round(u/t*100)):0},
            bool(v){return v?'enabled':'disabled'},seconds(v){return v<0?'disabled':v+'s'},clearFilters(){this.query='';this.stateFilter='all';this.typeFilter='all'}
        })));
    </script>
    <script defer src="/assets/alpine.js"></script>
</head>
<body>
<div class="shell">
    <header class="header" data-od-id="header">
        <div class="header-main">
            <div class="identity"><span class="mark">fr</span><div class="min"><div class="product">frpc dashboard</div><div class="endpoint mono" x-text="data?.server||'loading server'">loading server</div></div></div>
            <div class="actions">
                <span class="status" :class="connectionClass()"><span class="dot"></span><span class="status-label" x-text="connectionLabel()">Loading</span></span>
                <button class="btn icon-btn" type="button" @click="toggleTheme" :title="theme==='dark'?'Use light theme':'Use dark theme'" :aria-label="theme==='dark'?'Use light theme':'Use dark theme'" x-text="theme==='dark'?'L':'D'"></button>
                <button class="btn" type="button" @click="load()" :disabled="refreshing"><span x-text="refreshing?'...':'Refresh'"></span><span class="action-label" x-show="!refreshing"></span></button>
                <button class="btn" type="button" x-cloak x-show="data?.webuiAuthRequired" @click="logout()">Sign out</button>
            </div>
        </div>
        <nav class="subnav" aria-label="Dashboard sections"><a href="#proxies">Proxies</a><a href="#transport">Transport</a><a href="#work-connections">Work connections</a><a href="#events">Events</a></nav>
    </header>
    <main>
        <div class="notice" x-cloak x-show="error" role="alert"><div><strong>Status update failed</strong><span x-text="error"></span></div><button class="btn" @click="load()">Retry</button></div>
        <section class="metrics" aria-label="Client summary" data-od-id="summary">
            <div class="metric"><div class="label">Control channel</div><div class="value" x-text="connectionLabel()">Loading</div><div class="meta" x-text="data?.reconnectAttempt?'attempt '+data.reconnectAttempt:age(data?.stateChangedAt)"></div></div>
            <div class="metric"><div class="label">Proxies</div><div class="value mono" x-text="count('active')+' / '+proxies.length">0 / 0</div><div class="meta" x-text="count('error')?count('error')+' errors':count('pending')+' pending'"></div></div>
            <div class="metric"><div class="label">Active work conns</div><div class="value mono" x-text="data?.pool?.active??0">0</div><div class="meta" x-text="(data?.pool?.opening??0)+' opening / limit '+(data?.pool?.limit??data?.transport?.poolMax??0)"></div></div>
            <div class="metric"><div class="label">Accepted work</div><div class="value mono" x-text="data?.pool?.accepted??0">0</div><div class="meta" x-text="(data?.pool?.completed??0)+' completed'"></div></div>
            <div class="metric"><div class="label">Work failures</div><div class="value mono" x-text="(data?.pool?.rejected??0)+(data?.pool?.failed??0)">0</div><div class="meta" x-text="(data?.pool?.rejected??0)+' rejected / '+(data?.pool?.failed??0)+' failed'"></div></div>
            <div class="metric"><div class="label">Process uptime</div><div class="value mono" x-text="fmtDuration(data?.uptime)">0s</div><div class="meta" x-text="fmtBytes(data?.memory?.rss)+' RSS'"></div></div>
        </section>

        <div class="layout">
            <div class="left">
                <section class="panel" id="proxies" data-od-id="proxies">
                    <div class="panel-head"><div><h2 class="panel-title">Proxy status</h2><div class="panel-sub" x-text="proxies.length+' configured; select a row for details'"></div></div><div class="tools" x-show="!loading&&proxies.length"><input class="search" type="search" x-model.debounce.150ms="query" aria-label="Search proxies" placeholder="Search name, route, feature"><select class="select" x-model="stateFilter" aria-label="Filter by status"><option value="all">All states</option><option value="active">Active</option><option value="pending">Pending</option><option value="error">Error</option></select><select class="select" x-model="typeFilter" aria-label="Filter by type"><option value="all">All types</option><template x-for="t in types"><option :value="t" x-text="t.toUpperCase()"></option></template></select></div></div>
                    <div x-show="loading" aria-label="Loading proxy status"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div>
                    <div class="empty" x-cloak x-show="!loading&&!proxies.length"><div><h3>No proxies configured</h3><p>Add a proxy to the client configuration and restart frpc.</p></div></div>
                    <div class="empty" x-cloak x-show="!loading&&proxies.length&&!filtered.length"><div><h3>No matching proxies</h3><p>No proxy matches the current search and filters.</p><button class="btn" @click="clearFilters()">Clear filters</button></div></div>
                    <div class="table-wrap" x-cloak x-show="!loading&&filtered.length"><table><thead><tr><th style="width:22%">Name</th><th style="width:9%">Type</th><th style="width:22%">Remote route</th><th style="width:20%">Local target</th><th style="width:15%">Features</th><th style="width:12%">Status</th></tr></thead><template x-for="p in filtered" :key="p.name"><tbody><tr class="proxy-row"><td><button class="proxy-toggle" @click="expanded=expanded===p.name?null:p.name" :aria-expanded="expanded===p.name"><div class="proxy-name" x-text="p.name"></div><div class="bad-text" x-show="p.error" x-text="p.error"></div></button></td><td data-label="Type"><span class="type" x-text="p.type"></span></td><td class="proxy-route" data-label="Remote route" :title="p.remoteAddr||p.route||'Not assigned'" x-text="p.remoteAddr||p.route||'Not assigned'"></td><td class="proxy-local" data-label="Local target" :title="p.localTarget||'Not reported'" x-text="p.localTarget||'Not reported'"></td><td data-label="Features"><div class="tags"><template x-for="f in p.features"><span class="tag" x-text="f"></span></template><span class="tag" x-show="!p.features.length">default</span></div></td><td data-label="Status"><span class="status" :class="statusClass(p.status)"><span class="dot"></span><span x-text="p.status"></span></span></td></tr><tr class="detail-row" x-show="expanded===p.name"><td colspan="6"><div class="details"><div><div class="detail-label">Registered address</div><div class="detail-value mono" x-text="p.remoteAddr||'not assigned'"></div></div><div><div class="detail-label">Configured route</div><div class="detail-value mono" x-text="p.route||'not applicable'"></div></div><div><div class="detail-label">Last state change</div><div class="detail-value" x-text="age(p.updatedAt)"></div></div><template x-for="d in p.details"><div><div class="detail-label" x-text="d.label"></div><div class="detail-value" x-text="d.value"></div></div></template></div></td></tr></tbody></template></table></div>
                </section>

                <section class="panel" x-cloak x-show="visitors.length" data-od-id="visitors"><div class="panel-head"><div><h2 class="panel-title">Visitors</h2><div class="panel-sub" x-text="visitors.length+' configured'"></div></div></div><div class="visitor-list"><template x-for="v in visitors"><div class="visitor"><div><strong x-text="v.name"></strong><small x-text="v.type.toUpperCase()"></small></div><div><small>Local bind</small><span class="mono" x-text="v.bindAddr"></span></div><div><small>Server proxy</small><span class="mono" x-text="v.serverProxy"></span></div><span class="status" :class="statusClass(v.status)"><span class="dot"></span><span x-text="v.status"></span></span></div></template></div></section>
            </div>

            <aside class="right" aria-label="Client diagnostics">
                <section class="panel" id="transport" data-od-id="transport"><div class="panel-head"><div><h2 class="panel-title">Transport</h2><div class="panel-sub">Effective connection settings</div></div></div><div class="kv"><div class="kv-item"><div class="label">Wire protocol</div><div class="kv-value mono" x-text="data?.transport?.protocol||'-'"></div></div><div class="kv-item"><div class="label">TLS</div><div class="kv-value" :class="data?.transport?.tls?'flag-on':'flag-off'" x-text="bool(data?.transport?.tls)"></div></div><div class="kv-item"><div class="label">TLS verification</div><div class="kv-value" x-text="data?.transport?.tlsVerification||'-'"></div></div><div class="kv-item"><div class="label">TLS server name</div><div class="kv-value mono" x-text="data?.transport?.tlsServerName||data?.server||'-'"></div></div><div class="kv-item"><div class="label">TCP mux</div><div class="kv-value" :class="data?.transport?.tcpMux?'flag-on':'flag-off'" x-text="bool(data?.transport?.tcpMux)"></div></div><div class="kv-item"><div class="label">Pool range</div><div class="kv-value mono" x-text="(data?.transport?.poolMin??0)+' min / '+(data?.transport?.poolMax??0)+' max'"></div></div><div class="kv-item"><div class="label">TCP keepalive</div><div class="kv-value mono" x-text="seconds(data?.transport?.tcpKeepalive??-1)"></div></div><div class="kv-item"><div class="label">Mux keepalive</div><div class="kv-value mono" x-text="seconds(data?.transport?.muxKeepalive??-1)"></div></div><div class="kv-item"><div class="label">Heartbeat</div><div class="kv-value mono" x-text="seconds(data?.transport?.heartbeat??-1)"></div></div><div class="kv-item"><div class="label">Heartbeat timeout</div><div class="kv-value mono" x-text="seconds(data?.transport?.heartbeatTimeout??-1)"></div></div><div class="kv-item"><div class="label">Retry limit</div><div class="kv-value mono" x-text="data?.transport?.retries||'unlimited'"></div></div><div class="kv-item"><div class="label">Log level</div><div class="kv-value mono" x-text="data?.client?.logLevel||'-'"></div></div></div></section>

                <section class="panel" id="work-connections" data-od-id="work-connections"><div class="panel-head"><div><h2 class="panel-title">Work connections</h2><div class="panel-sub" x-text="'Last activity '+age(data?.pool?.lastActivity)"></div></div></div><div class="pool-grid"><div class="pool-item"><div class="label">Requested</div><div class="pool-number" x-text="data?.pool?.requested??0"></div></div><div class="pool-item"><div class="label">Accepted</div><div class="pool-number" x-text="data?.pool?.accepted??0"></div></div><div class="pool-item"><div class="label">Completed</div><div class="pool-number" x-text="data?.pool?.completed??0"></div></div><div class="pool-item"><div class="label">Rejected</div><div class="pool-number" x-text="data?.pool?.rejected??0"></div></div><div class="pool-item"><div class="label">Failed</div><div class="pool-number" x-text="data?.pool?.failed??0"></div></div><div class="pool-item"><div class="label">Pool limited</div><div class="pool-number" x-text="data?.pool?.limited??0"></div></div></div></section>

                <section class="panel" data-od-id="runtime"><div class="panel-head"><div><h2 class="panel-title">Client runtime</h2><div class="panel-sub">Process and identity</div></div></div><div class="kv"><div class="kv-item"><div class="label">Run ID</div><div class="kv-value mono" x-text="data?.runId||'not assigned'"></div></div><div class="kv-item"><div class="label">Platform</div><div class="kv-value mono" x-text="data?data.os+' / '+data.arch:'-'"></div></div><div class="kv-item"><div class="label">User</div><div class="kv-value mono" x-text="data?.client?.user||'(default)'"></div></div><div class="kv-item"><div class="label">Client ID</div><div class="kv-value mono" x-text="data?.client?.clientId||'(generated)'"></div></div><div class="kv-item"><div class="label">Authentication</div><div class="kv-value" x-text="data?.client?.authMethod||'-'"></div></div><div class="kv-item"><div class="label">Heap</div><div class="kv-value mono"><span x-text="fmtBytes(data?.memory?.heapUsed)"></span> / <span x-text="fmtBytes(data?.memory?.heapTotal)"></span></div><div class="memory"><span :style="'width:'+memoryPercent()+'%'"></span></div></div></div></section>

                <section class="panel" id="events" data-od-id="events"><div class="panel-head"><div><h2 class="panel-title">Recent events</h2><div class="panel-sub">Latest 40 state transitions</div></div></div><div class="events"><div class="empty" x-show="!events.length"><div><h3>No events yet</h3><p>Connection and proxy state changes will appear here.</p></div></div><template x-for="e in events" :key="e.id"><div class="event"><time class="event-time" x-text="time(e.at)"></time><span class="event-mark" :class="e.level"></span><div class="event-text" x-text="e.message"></div></div></template></div></section>
            </aside>
        </div>
        <div class="foot" aria-live="polite"><span x-text="'Updated '+age(data?.updatedAt)"></span> / polling every 2s</div>
    </main>
</div>
</body>
</html>`;
